### ISSUE TITLE
[CHAT] 채팅방 생성 구현

### ISSUE THREAD

**Issue by ykc0131** [One-Trillion-Club/HUMATE-BackEnd#6]
## 🍀 Description
채팅방 생성 기능을 구현한다.

## ✅ Todo
- [x] 채팅방을 새로 생성하는 메소드 구현
- [ ] 채팅방ID를 UUID로 생성하는 메소드 구현 -> (안하기로 함)
- [x] 입장하는 메소드 구현
