### ISSUE TITLE
[ACTIVITY] 완료된 동행에 대해서 활동 업로드 할 수 없도록 변경

### ISSUE THREAD

**Issue by Hypersand** [One-Trillion-Club/HUMATE-BackEnd#88]
## 🍀 Description
활동 관련 검증 로직 및 추가 데이터가 필요한 로직에 데이터를 넣겠습니다.

## ✅ Todo
- [ ] 동행이 종료되었다면 새로운 활동일지라도 업로드할 수 없다.
- [ ] 동행 목록 데이터 반환 시 match_branch 추가
- [ ] S3 Upload 비동기 처리

## ETC
기타사항
